version: "3.2"

services:
  node-subtensor:
    container_name: node-paratensor
    image: opentensorfdn/rinzler:0.0.1
    cpu_count: 4
    mem_limit: 10000000000
    memswap_limit: 20000000000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "9944:9944"
      - "30333:30333"
      - "30334:30334"
      - "9945:9945"
      - "9946:9946"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    command: bash -c "/usr/local/bin/paratensor --chain paratensor/specs/finney_rococo_raw.json --base-path /tmp/parachain/paratensor --port 30333 --rpc-cors all --rpc-port 9944 --ws-port 9945 --bootnodes /ip4/164.92.84.57/tcp/40334/p2p/12D3KooWRGV7Aem9hJYXpBWBrZrFNnyrD3GxuhsVto2aAdiqYHys -- --execution wasm --chain paratensor/specs/rococo_raw_spec.json  --port 30334 --ws-port 9946 --rpc-cors all --bootnodes /ip4/137.184.147.81/tcp/30333/p2p/12D3KooWJPcxdiKNq2HDJ7kZN8XTaTmx6c87YcKnWywrfSSE4Tui --sync warp"
