[relaychain]
default_command = "./bin/polkadot-v0.9.32"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"
  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "dev"

  [parachains.collator]
  name = "rinzler-collator-01"
  command = "./paratensor"