[relaychain]
default_command = "zombienet/polkadot/target/release/polkadot"
default_args = [ "-lparachain=debug" ]    

chain = "rococo-local"
  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "dev"

  [parachains.collator]
  name = "parachain-A-1000-collator-01"
  command = "target/release/paratensor"
  ws_port = "{{ZOMB_WS_PORT}}"